#+TITLE: Configuration and analysis for "Effective radiative forcing in the aerosol-climate model CAM5.3-MARC-ARG"
#+AUTHOR: Benjamin S. Grandey
#+OPTIONS: ^:nil

[[https://zenodo.org/badge/latestdoi/96524970][https://zenodo.org/badge/96524970.svg]]

** Introduction
This repository contains details of the experimental design, model configuration, data management, and analysis procedure for the manuscript titled "Effective radiative forcing in the aerosol-climate model CAM5.3-MARC-ARG" by B. S. Grandey, D. Rothenberg, A. Avramov, Q. Jin, H.-H. Lee, X. Liu, Z. Lu, S. Albani, and C. Wang.

** Purpose
Configure and analyse [[http://www.cesm.ucar.edu/][CESM]] simulations in order to compare [[https://doi.org/10.5281/zenodo.1117370][/MARC/ (the /two-Moment, Multi-Modal, Mixing-state-resolving Aerosol model for Research of Climate/)]] and [[http://www.geosci-model-dev.net/5/709/2012/][MAM]].

** Contents
1. [[https://github.com/grandey/p17c-marc-comparison/blob/master/experimental_design.org][experimental_design.org]] provides an introduction to the *experimental design*.
2. [[https://github.com/grandey/p17c-marc-comparison/tree/master/input_data_p17c][input_data_p17c/]] contains information and scripts relating to the *input data*.
3. [[https://github.com/grandey/p17c-marc-comparison/tree/master/user_nl_cam][user_nl_cam/]] contains the =user_nl_cam= namelist files for the simulations.
4. [[https://github.com/grandey/p17c-marc-comparison/tree/master/config_simulations][config_simulations/]] contains information and scripts for *creating, building, and submitting* the simulations. [[https://github.com/grandey/p17c-marc-comparison/blob/master/config_simulations/config_comparison_simulations.org][config_comparison_simulations.org]] and [[https://github.com/grandey/p17c-marc-comparison/blob/master/config_simulations/config_timing_simulations.org][config_timing_simulations.org]] are used to generate the scripts.
5. [[https://github.com/grandey/p17c-marc-comparison/tree/master/manage_data][manage_data/]] contains information and scripts for *managing* the simulation *output data*. [[https://github.com/grandey/p17c-marc-comparison/blob/master/manage_data/data_management.org][data_management.org]] provides the details.
6. [[https://github.com/grandey/p17c-marc-comparison/tree/master/analysis_prelim][analysis_prelim/]] contains scripts used for *preliminary analysis* of the simulation output data.
7. [[https://github.com/grandey/p17c-marc-comparison/tree/master/analysis_draft2017b/][analysis_draft2017b/]] contains scripts used for the *final analysis* of the simulation output data, including generation of the *figures* included in the manuscript.

** Model input and output data
The model input data and the subset of the model output data analysed have been uploaded to Figshare: https://doi.org/10.6084/m9.figshare.5687812.

** Author
Benjamin S. Grandey, 2017-2018, in collaboration with Daniel Rothenberg, Alexander Avramov, Qinjian Jin, Hsiang-He Lee, Xiaohong Liu, Zheng Lu, Samuel Albani, and Chien Wang.

** Acknowledgements
This research is supported by the National Research Foundation of Singapore under its Campus for Research Excellence and Technological Enterprise programme. The Center for Environmental Sensing and Modeling is an interdisciplinary research group of the Singapore-MIT Alliance for Research and Technology.  This research is also supported by the U.S. National Science Foundation (AGS-1339264) and the U.S. Department of Energy, Office of Science (DE-FG02-94ER61937). The CESM project is supported by the National Science Foundation and the Office of Science (BER) of the U.S. Department of Energy. We acknowledge high-performance computing support from Cheyenne ([[https://doi.org/10.5065/D6RX99HX][doi:10.5065/D6RX99HX]]) provided by NCAR’s Computational and Information Systems Laboratory, sponsored by the National Science Foundation. We thank Natalie Mahowald for contributing dust model code, optical tables, a soil erodibility map, and advice, all of which have aided the development of CAM5.3-MARC-ARG.

** Primary reference
Grandey, B. S., Rothenberg, D., Avramov, A., Jin, Q., Lee, H.-H., Liu, X., Lu, Z., Albani, S., and Wang, C.: Effective radiative forcing in the aerosol–climate model CAM5.3-MARC-ARG, Atmos. Chem. Phys. Discuss., https://doi.org/10.5194/acp-2018-118, in review, 2018.
