#+TITLE: p17c-marc-comparison/manage_data/data_management.org
#+AUTHOR: Benjamin S. Grandey

** Data management

*** Saving a copy of the output data to Newton
Please see [[https://github.com/grandey/p17c-marc-comparison/blob/master/manage_data/archive_case_dir_p17c.sh][archive_case_dir_p17c.sh]], [[https://github.com/grandey/p17c-marc-comparison/blob/master/manage_data/gzip_netcdf_p17c.sh][gzip_netcdf_p17c.sh]], and [[https://github.com/grandey/p17c-marc-comparison/blob/master/manage_data/rsync_archive_to_newton.sh][rsync_archive_to_newton.sh]], which outline the workflow for the data from the comparison simulations.

Update 2018-06-07: Data from the =p17c_mam7_1850= simulation have been separately saved to Newton, using some of the code contained in the three scripts mentioned above.

*** Converting from time-slice to time-series format
After gunzipping a copy of the output history files on Newton, [[https://github.com/NCAR/PyReshaper][PyReshaper]] (v1.0.1) can be used to convert to time-series format. I have =PyReshaper= installed in a separate =conda= environment:

#+BEGIN_SRC
source activate pyreshaper
#+END_SRC

**** Converting atmospheric h0 data to time-series format

First, =s2make= is used to generate a specifier file, e.g. for atmosphere output:

#+BEGIN_SRC
CASENAME=p17c_marc_2000

IN_DIR=/somerset/grandey/data4/acrc/RUN/unzipped/$CASENAME/atm/hist
OUT_DIR=/dhobyghaut/grandey/data5/cesm/s2s/$CASENAME/atm

mkdir -p $OUT_DIR

s2smake \
    --netcdf_format="netcdf4" \
    --compression_level=1 \
    --output_prefix="$OUT_DIR/$CASENAME.cam.h0." \
    --output_suffix=".nc" \
    -m "time" -m "time_bnds" -m "ch4vmr" -m "co2vmr" -m "f11vmr" \
    -m "time_written" -m "n2ovmr" -m "date_written" -m "f12vmr" \
    -m "sol_tsi" -m "nsteph" -m "datesec" -m "ndcur" -m "date" \
    -m "nscur" \
    --specfile=$OUT_DIR/specfile_$CASENAME.s2s \
    $IN_DIR/$CASENAME.cam.h0.????-??.nc
#+END_SRC

(The metadata field information (indicated by =m=) has been copied from some example code Daniel Rothenberg kindly provided.)

Second, =s2run= is run in parallel in order to convert the data to time-series format:

#+BEGIN_SRC
mpirun -n 8 s2srun --verbosity=2 $OUT_DIR/specfile_$CASENAME.s2s
#+END_SRC

**** Converting land h0 data to time-series format

#+BEGIN_SRC
CASENAME_LIST="p17c_mam3_2000 p17c_mam3_1850 p17c_mam7_2000 p17c_marc_2000 p17c_marc_1850"
for CASENAME in $CASENAME_LIST
do
  IN_DIR=/somerset/grandey/data4/acrc/RUN/unzipped/$CASENAME/lnd/hist
  OUT_DIR=/dhobyghaut/grandey/data5/cesm/s2s/$CASENAME/lnd
  mkdir -p $OUT_DIR
  s2smake \
    --netcdf_format="netcdf4" \
    --compression_level=1 \
    --output_prefix="$OUT_DIR/$CASENAME.clm2.h0." \
    --output_suffix=".nc" \
    -m "time" -m "time_bounds" \
    -m "mcdate" -m "mcsec" -m "mdcur" -m "mscur" -m "nstep" \
    -m "date_written" -m "time_written" \
    --specfile=$OUT_DIR/specfile_$CASENAME.s2s \
    $IN_DIR/$CASENAME.clm2.h0.????-??.nc
  mpirun -n 8 s2srun --verbosity=2 $OUT_DIR/specfile_$CASENAME.s2s
done
#+END_SRC

**** Converting ice data to time-series format

#+BEGIN_SRC
CASENAME_LIST="p17c_mam3_2000 p17c_mam3_1850 p17c_mam7_2000 p17c_marc_2000 p17c_marc_1850"
for CASENAME in $CASENAME_LIST
do
  IN_DIR=/somerset/grandey/data4/acrc/RUN/unzipped/$CASENAME/ice/hist
  OUT_DIR=/dhobyghaut/grandey/data5/cesm/s2s/$CASENAME/ice
  mkdir -p $OUT_DIR
  s2smake \
    --netcdf_format="netcdf4" \
    --compression_level=1 \
    --output_prefix="$OUT_DIR/$CASENAME.cice.h." \
    --output_suffix=".nc" \
    -m "time" -m "time_bounds" \
    --specfile=$OUT_DIR/specfile_$CASENAME.s2s \
    $IN_DIR/$CASENAME.cice.h.????-??.nc
  mpirun -n 8 s2srun --verbosity=2 $OUT_DIR/specfile_$CASENAME.s2s
done
#+END_SRC

**** Converting =p17c_mam7_1850= data to time-series format

Update 2018-06-07: Data from the =p17c_mam7_1850= simulation have been separately converted to time-series format, using the same methodology as for the five other comparison simulations.

*** Syncing to local machine for analysis
Data of interest can then be pulled from Newton using rsync.

**** Syncing atmosphere output data
Note: some variable names differ between MARC and MAM3, and MAM7.

MARC fields of interest:

#+BEGIN_SRC
CASENAME_LIST="p17c_marc_2000 p17c_marc_1850"
VARIABLE_LIST=" \
FSNTOA FSNTOANOA FSNTOACNOA FSNS FSNSNOA CRF LWCF \
OC_LDG \
TAU_tot \
TGCLDLWP TGCLDIWP TGCLDCWP CDNUMC \
CLDTOT CLDLOW CLDMED CLDHGH \
PRECC PRECL PRECSC PRECSL \
U10 \
PS PSL \
mNUC mAIT mACC \
mOC mMOS mOIM mBC mMBS mBIM \
SSLT01 SSLT02 SSLT03 SSLT04 \
DST01 DST02 DST03 DST04 \
mOCSF mBCSF DST01SF DST02SF DST03SF DST04SF SSLT01SF SSLT02SF SSLT03SF SSLT04SF \
mACCDRY mAITDRY mNUCDRY mOCDRY mMOSDRY mOIMDRY mBCDRY mMBSDRY mBIMDRY \
DST01DD DST02DD DST03DD DST04DD SSLT01DD SSLT02DD SSLT03DD SSLT04DD \
mACCWET mAITWET mNUCWET mOCWET mMOSWET mOIMWET mBCWET mMBSWET mBIMWET \
DST01PP DST02PP DST03PP DST04PP SSLT01PP SSLT02PP SSLT03PP SSLT04PP \
AGEmOC AGEmMOS AGEmBC AGEmMBS \
mACCACT mAITACT mNUCACT mOCACT mMOSACT mOIMACT mBCACT mMBSACT mBIMACT \
mACCSCV mAITSCV mNUCSCV mOCSCV mMOSSCV mOIMSCV mBCSCV mMBSSCV mBIMSCV \
mSO4evap \
BNUCmNUC \
CNDmACC CNDmAIT CNDmNUC CNDmMOS CNDmMBS \
MVmNUC MVmAIT \
CGmNUCAC CGmNUCAI CGmNUCMB CGmNUCMO CGmAITAC CGmAITMB CGmAITMO CGmACCMB CGmACCMO CGmOCMOS \
CCN3"
#+END_SRC

MAM fields of interest:

#+BEGIN_SRC
CASENAME_LIST="p17c_mam3_2000 p17c_mam3_1850 p17c_mam7_2000 p17c_mam7_1850"
VARIABLE_LIST=" \
FSNTOA FSNTOA_d1 FSNTOAC_d1 FSNS FSNS_d1 SWCF_d1 LWCF \
BURDENSO4 BURDENPOM BURDENBC BURDENSEASALT BURDENDUST \
AEROD_v \
TGCLDLWP TGCLDIWP TGCLDCWP CDNUMC \
CLDTOT CLDLOW CLDMED CLDHGH \
PRECC PRECL PRECSC PRECSL \
U10 \
CCN3"
#+END_SRC

Rsync command:

#+BEGIN_SRC
for CASENAME in $CASENAME_LIST
do
  for VARIABLE in $VARIABLE_LIST
  do
    rsync -av --progress -e "ssh -p $NEWTON_PORT" \
        $NEWTON_USER@$NEWTON_IP:/dhobyghaut/grandey/data5/cesm/s2s/$CASENAME/atm/$CASENAME.cam.h0.$VARIABLE.nc \
        $HOME/data/projects/p17c_marc_comparison/output_timeseries/
  done
done
#+END_SRC

**** Syncing land output data

#+BEGIN_SRC
CASENAME_LIST="p17c_mam3_2000 p17c_mam3_1850 p17c_mam7_2000 p17c_mam7_1850 p17c_marc_2000 p17c_marc_1850"
VARIABLE_LIST="FSNO SNOBCMSL BCDEP"

for CASENAME in $CASENAME_LIST
do
  for VARIABLE in $VARIABLE_LIST
  do
    rsync -av --progress -e "ssh -p $NEWTON_PORT" \
        $NEWTON_USER@$NEWTON_IP:/dhobyghaut/grandey/data5/cesm/s2s/$CASENAME/lnd/$CASENAME.clm2.h0.$VARIABLE.nc \
        $HOME/data/projects/p17c_marc_comparison/output_timeseries/
  done
done
#+END_SRC

**** Syncing ice output data

#+BEGIN_SRC
CASENAME_LIST="p17c_mam3_2000 p17c_mam3_1850 p17c_mam7_2000 p17c_mam7_1850 p17c_marc_2000 p17c_marc_1850"
VARIABLE_LIST="fs"

for CASENAME in $CASENAME_LIST
do
  for VARIABLE in $VARIABLE_LIST
  do
    rsync -av --progress -e "ssh -p $NEWTON_PORT" \
        $NEWTON_USER@$NEWTON_IP:/dhobyghaut/grandey/data5/cesm/s2s/$CASENAME/ice/$CASENAME.cice.h.$VARIABLE.nc \
        $HOME/data/projects/p17c_marc_comparison/output_timeseries/
  done
done
#+END_SRC

**** Syncing timing data from timing simulations

#+BEGIN_SRC
CASENAME_LIST="p17c_t_marc_r2 p17c_t_marc_r1 p17c_t_mam3_r2 p17c_t_mam3_r1 p17c_t_mam7_r2 p17c_t_mam7_r1"

for CASENAME in $CASENAME_LIST
do
  rsync -av --progress -e "ssh -p $NEWTON_PORT" \
        $NEWTON_USER@$NEWTON_IP:/orchard/grandey/data2/acrc/RUN/archive/$CASENAME/arch_case/$CASENAME/timing/ccsm_timing.* \
        $HOME/data/projects/p17c_marc_comparison/output_timing/
done
#+END_SRC

*** Uploading data to Figshare

**** WAIT Input data - add p17c_mam7_1850 NH3 emissions file

=input_data_p17c.tar.gz=, orginally created on 2017-07-21, has been uploaded. It contains the scripts used to generate the MARC input data (see https://github.com/grandey/p17c-marc-comparison/tree/master/input_data_p17c) and the input data NetCDF files.

**** WAIT Output timeseries data from comparison simulations - add p17c_mam7_1850 output

A subset of the atmosphere, land, and ice output NetCDF files have been previously synced to =$HOME/data/projects/p17c_marc_comparison/output_timeseries/= on the local machine (see above). The total size is approximately 18GB. These files have been uploaded.

**** DONE Timing data from timing simulations
CLOSED: [2017-12-11 Mon 19:03]

The timing data from the timing files have been previously synced to =$HOME/data/projects/p17c_marc_comparison/output_timing/= on the local machine (see above). A compressed tarball, created using =tar -cvzf output_timing.tar.gz output_timing/=, has been uploaded.

**** History of Figshare publication
- 2017-12-11 - Uploading data. Title: Data for "Effective radiative forcing in the aerosol-climate model CAM5.3-MARC-ARG compared to default CAM5.3". Entering categories, keywords, and description. Reserving DOI. Re-uploading some failed transfers. Publishing v1. [[https://doi.org/10.6084/m9.figshare.5687812.v1]].
- 2018-02-01 - Changes to title and description, to correspond with v5 of draft manuscript. Publishing [[https://doi.org/10.6084/m9.figshare.5687812.v2]].
