#+TITLE: Configure comparison simulations
#+AUTHOR: Benjamin S. Grandey
#+OPTIONS: ^:nil

** General notes

*** Experimental design
For an overview of the experimental design, please see [[https://github.com/grandey/p17c-marc-comparison/blob/master/experimental_design.org][experimental_design.org]].

*** CESM versions
- The MAM3 and MAM7 simulations use CESM 1.2.2.1 (CESM 1.2.2 configured for Cheyenne), found in =~/models/cesm1_2_2_1=.
- The MARC simulations use a version of CESM 1.2.2.1 containing MARC (git commit =ff48dbe=), found in =~/models/cesm1221_marc=.

*** Processor layout
All simulations will be configured with a layout of =NTASKS=720= for all model components, spread across 20 nodes.

*** =user_nl_cam= files
The =user_nl_cam= files will be pulled from GitHub using =wget=.

*** COSP bug fix
In order to fix [[https://bb.cgd.ucar.edu/bug-cosp-simulator][a bug in COSP]], a modified version of =cospsimulator_intr.F90= will be used. The modification is as follows:

#+BEGIN_SRC 
1974c1974
<             mr_ccice(i,k) = sh_cldliq(i,k) + dp_cldliq(i,k)
---
>             mr_ccice(i,k) = sh_cldice(i,k) + dp_cldice(i,k)
#+END_SRC

*** Symbolic link to run directory
To facilitate ease of access to the run directory, I like to create a symbolic link (=ln -s /glade/scratch/bgrandey/$CASENAME/run/ scratch_run=).

*** Submission to the =economy= queue
By default, my =.run= files are configured for submission to the =regular= queue. In order to submit to the =economy= queue, the =.run= file can be modified using =sed -i 's/regular/economy/g' $CASENAME.run=.

** Creation, configuration, and submission of comparison simulations

The source code blocks below are tangled using =C-c C-v t= in order to create bash scripts named =create_<CASENAME>.sh=.
The original five comparison simulations have been created, configured, built, and submitted using these bash scripts on 2017-07-21.
The sixth comparison simulation (=p17c_mam7_2000=) has been created, configured, built, and submitted using the sixth bash script on 2018-06-06.

*** DONE =p17c_marc_2000=
CLOSED: [2017-07-21 Fri 14:38]

#+BEGIN_SRC :tangle yes :tangle create_p17c_marc_2000.sh :shebang #!/bin/bash
CASENAME=p17c_marc_2000

cd ~/models/cesm1221_marc/scripts/
./create_newcase -case ~/cesm1_2_2_1_cases/$CASENAME -res f19_g16 -compset FC5MARC -mach cheyenne -pes_file pes/p720n20.xml

cd ~/cesm1_2_2_1_cases/$CASENAME
./xmlchange CAM_CONFIG_OPTS="-phys cam5 -chem trop_marc -cosp"
./cesm_setup
wget https://raw.githubusercontent.com/grandey/p17c-marc-comparison/master/user_nl_cam/user_nl_cam_$CASENAME
mv user_nl_cam_$CASENAME user_nl_cam
cp ~/models/mySourceMods/cospsimulator_intr.F90 SourceMods/src.cam/
./$CASENAME.build
ln -s /glade/scratch/bgrandey/$CASENAME/run/ scratch_run
./xmlchange STOP_OPTION=nyears
./xmlchange STOP_N=8
./xmlchange RESUBMIT=3
sed -i 's/regular/economy/g' $CASENAME.run
./$CASENAME.submit
#+END_SRC

Notes:
- Model directory is =~/models/cesm1221_marc/=.
- =compset= is =FC5MARC=.
- =CAM_CONFIG_OPTS= are =-phys cam5 -chem trop_marc -cosp=.
- Case created, configured, built, and submitted on 2017-07-21.

*** DONE =p17c_marc_1850=
CLOSED: [2017-07-21 Fri 14:39]

#+BEGIN_SRC :tangle yes :tangle create_p17c_marc_1850.sh :shebang #!/bin/bash
CASENAME=p17c_marc_1850

cd ~/models/cesm1221_marc/scripts/
./create_newcase -case ~/cesm1_2_2_1_cases/$CASENAME -res f19_g16 -compset FC5MARC -mach cheyenne -pes_file pes/p720n20.xml

cd ~/cesm1_2_2_1_cases/$CASENAME
./xmlchange CAM_CONFIG_OPTS="-phys cam5 -chem trop_marc -cosp"
./cesm_setup
wget https://raw.githubusercontent.com/grandey/p17c-marc-comparison/master/user_nl_cam/user_nl_cam_$CASENAME
mv user_nl_cam_$CASENAME user_nl_cam
cp ~/models/mySourceMods/cospsimulator_intr.F90 SourceMods/src.cam/
./$CASENAME.build
ln -s /glade/scratch/bgrandey/$CASENAME/run/ scratch_run
./xmlchange STOP_OPTION=nyears
./xmlchange STOP_N=8
./xmlchange RESUBMIT=3
sed -i 's/regular/economy/g' $CASENAME.run
./$CASENAME.submit
#+END_SRC

Notes:
- Same as =p17c_marc_2000= above, but with different =$CASENAME= (and =user_nl_cam= file).
- Case created, configured, built, and submitted on 2017-07-21.

*** DONE =p17c_mam3_2000=
CLOSED: [2017-07-21 Fri 14:40]

#+BEGIN_SRC :tangle yes :tangle create_p17c_mam3_2000.sh :shebang #!/bin/bash
CASENAME=p17c_mam3_2000

cd ~/models/cesm1_2_2_1/scripts/
./create_newcase -case ~/cesm1_2_2_1_cases/$CASENAME -res f19_g16 -compset FC5 -mach cheyenne -pes_file pes/p720n20.xml

cd ~/cesm1_2_2_1_cases/$CASENAME
./xmlchange CAM_CONFIG_OPTS="-phys cam5 -cosp"
./cesm_setup
wget https://raw.githubusercontent.com/grandey/p17c-marc-comparison/master/user_nl_cam/user_nl_cam_$CASENAME
mv user_nl_cam_$CASENAME user_nl_cam
cp ~/models/mySourceMods/cospsimulator_intr.F90 SourceMods/src.cam/
./$CASENAME.build
ln -s /glade/scratch/bgrandey/$CASENAME/run/ scratch_run
./xmlchange STOP_OPTION=nyears
./xmlchange STOP_N=8
./xmlchange RESUBMIT=3
sed -i 's/regular/economy/g' $CASENAME.run
./$CASENAME.submit
#+END_SRC

Notes:
- Model directory is =~/models/cesm1_2_2_1/=.
- =compset= is =FC5=.
- =CAM_CONFIG_OPTS= are =-phys cam5 -cosp=.
- Case created, configured, built, and submitted on 2017-07-21.
- Run failed after 4th start on 2017-07-21. Re-submitted on 2017-08-03.

*** DONE =p17c_mam3_1850=
CLOSED: [2017-07-21 Fri 14:41]

#+BEGIN_SRC :tangle yes :tangle create_p17c_mam3_1850.sh :shebang #!/bin/bash
CASENAME=p17c_mam3_1850

cd ~/models/cesm1_2_2_1/scripts/
./create_newcase -case ~/cesm1_2_2_1_cases/$CASENAME -res f19_g16 -compset FC5 -mach cheyenne -pes_file pes/p720n20.xml

cd ~/cesm1_2_2_1_cases/$CASENAME
./xmlchange CAM_CONFIG_OPTS="-phys cam5 -cosp"
./cesm_setup
wget https://raw.githubusercontent.com/grandey/p17c-marc-comparison/master/user_nl_cam/user_nl_cam_$CASENAME
mv user_nl_cam_$CASENAME user_nl_cam
cp ~/models/mySourceMods/cospsimulator_intr.F90 SourceMods/src.cam/
./$CASENAME.build
ln -s /glade/scratch/bgrandey/$CASENAME/run/ scratch_run
./xmlchange STOP_OPTION=nyears
./xmlchange STOP_N=8
./xmlchange RESUBMIT=3
sed -i 's/regular/economy/g' $CASENAME.run
./$CASENAME.submit
#+END_SRC

Notes:
- Same as =p17c_mam3_2000= above, but with different =$CASENAME= (and =user_nl_cam= file).
- Case created, configured, built, and submitted on 2017-07-21.

*** DONE =p17c_mam7_2000=
CLOSED: [2017-07-21 Fri 14:42]

#+BEGIN_SRC :tangle yes :tangle create_p17c_mam7_2000.sh :shebang #!/bin/bash
CASENAME=p17c_mam7_2000

cd ~/models/cesm1_2_2_1/scripts/
./create_newcase -case ~/cesm1_2_2_1_cases/$CASENAME -res f19_g16 -compset FC5 -mach cheyenne -pes_file pes/p720n20.xml

cd ~/cesm1_2_2_1_cases/$CASENAME
./xmlchange CAM_CONFIG_OPTS="-phys cam5 -chem trop_mam7 -cosp"
./cesm_setup
wget https://raw.githubusercontent.com/grandey/p17c-marc-comparison/master/user_nl_cam/user_nl_cam_$CASENAME
mv user_nl_cam_$CASENAME user_nl_cam
cp ~/models/mySourceMods/cospsimulator_intr.F90 SourceMods/src.cam/
./$CASENAME.build
ln -s /glade/scratch/bgrandey/$CASENAME/run/ scratch_run
./xmlchange STOP_OPTION=nyears
./xmlchange STOP_N=8
./xmlchange RESUBMIT=3
sed -i 's/regular/economy/g' $CASENAME.run
./$CASENAME.submit
#+END_SRC

Notes:
- Model directory is =~/models/cesm1_2_2_1/=.
- =compset= is =FC5=.
- =CAM_CONFIG_OPTS= are =-phys cam5 -chem trop_mam7 -cosp=.
- Case created, configured, built, and submitted on 2017-07-21.

*** DONE =p17c_mam7_1850=
CLOSED: [2018-06-06 Wed 17:54]

#+BEGIN_SRC :tangle yes :tangle create_p17c_mam7_1850.sh :shebang #!/bin/bash
CASENAME=p17c_mam7_1850

cd ~/models/cesm1_2_2_1/scripts/
./create_newcase -case ~/cesm1_2_2_1_cases/$CASENAME -res f19_g16 -compset FC5 -mach cheyenne -pes_file pes/p720n20.xml

cd ~/cesm1_2_2_1_cases/$CASENAME
./xmlchange CAM_CONFIG_OPTS="-phys cam5 -chem trop_mam7 -cosp"
./cesm_setup
wget https://raw.githubusercontent.com/grandey/p17c-marc-comparison/master/user_nl_cam/user_nl_cam_$CASENAME
mv user_nl_cam_$CASENAME user_nl_cam
cp ~/models/mySourceMods/cospsimulator_intr.F90 SourceMods/src.cam/
./$CASENAME.build
ln -s /glade/scratch/bgrandey/$CASENAME/run/ scratch_run
./xmlchange STOP_OPTION=nyears
./xmlchange STOP_N=8
./xmlchange RESUBMIT=3
sed -i 's/regular/economy/g' $CASENAME.run
./$CASENAME.submit
#+END_SRC

Notes:
- Model directory is =~/models/cesm1_2_2_1/=.
- =compset= is =FC5=.
- =CAM_CONFIG_OPTS= are =-phys cam5 -chem trop_mam7 -cosp=.
- Case created, configured, built, and submitted on 2018-06-06.
